// SPDX-License-Identifier: Apache-2.0

/**
 * Ergonomic aliases over the generated OpenAPI types.
 *
 * The generated `components["schemas"]` map is the source of truth
 * (regenerated by `cargo xtask check-contracts`, drift-checked in CI);
 * these aliases give them their natural names back.
 *
 * @packageDocumentation
 */

import type { components } from "./generated/api.js";

type Schemas = components["schemas"];

// Pairing (SPEC §2.A) — stable.
export type PairRequest = Schemas["PairRequest"];
export type PairResponse = Schemas["PairResponse"];
export type PairInfo = Schemas["PairInfo"];
export type Scope = Schemas["Scope"];

// Sessions (SPEC §5.A) — stable.
export type CreateSessionResponse = Schemas["CreateSessionResponse"];
export type Turn = Schemas["Turn"];
export type Draft = Schemas["Draft"];

// Suggestions (SPEC §5.A) — stable.
export type SuggestRequest = Schemas["SuggestRequest"];
export type SuggestEvent = Schemas["SuggestEvent"];
export type Suggestion = Schemas["Suggestion"];
export type NextCharsResponse = Schemas["NextCharsResponse"];

// Input (SPEC §4.A) — stable.
export type TargetMap = Schemas["TargetMap"];
export type SelectionEvent = Schemas["SelectionEvent"];
export type InputClientMessage = Schemas["InputClientMessage"];

// Voice (SPEC §6) — stable.
export type SpeakRequest = Schemas["SpeakRequest"];
export type VoicesResponse = Schemas["VoicesResponse"];

// System (SPEC §2.C) — stable.
export type HealthResponse = Schemas["HealthResponse"];
export type CapabilitiesResponse = Schemas["CapabilitiesResponse"];
export type EmergencyRequest = Schemas["EmergencyRequest"];
export type SystemEvent = Schemas["SystemEvent"];
export type ServerFrame = Schemas["ServerFrame"];
export type Topic = Schemas["Topic"];

// Errors (RFC 9457).
export type Problem = Schemas["Problem"];
export type ErrorCode = Schemas["ErrorCode"];

// Memory (SPEC §5.B) — experimental: may change until Phase 9.
export type MemoryItem = Schemas["MemoryItem"];
export type CreateMemoryItem = Schemas["CreateMemoryItem"];
export type MemorySearchResponse = Schemas["MemorySearchResponse"];
export type PendingResponse = Schemas["PendingResponse"];
export type ForgetRequest = Schemas["ForgetRequest"];
export type ForgetCandidates = Schemas["ForgetCandidates"];

// ASR consent (SPEC §5.A) — experimental.
export type ConsentResponse = Schemas["ConsentResponse"];
export type ListeningRequest = Schemas["ListeningRequest"];

// Profiles (SPEC §7.B) — experimental.
export type Profile = Schemas["Profile"];
