// SPDX-License-Identifier: Apache-2.0

//! The acceleration engine API: `/suggest` (SSE) and `/next-chars`
//! (SPEC §5.A — the heart).
//!
//! Four modes share context, memory retrieval and style profile; only the
//! prompts/LoRA differ. Per-slot cancellation lives server-side: a new
//! request on the same slot aborts the previous one (the debounce belongs
//! to the hub, not to each UI).
//!
//! Stability: **stable** (A1 core).

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::common::{Normalized, ProfileId, SlotId};

/// `POST /sessions/{id}/suggest` request (SPEC §5.A).
///
/// Wire example:
/// `{"mode":"rephrase","draft":"veu eau frache ce soir","n":3,"slot":"main",`
/// `"constraints":{"max_chars":120,"register":"famille"},"style_profile":"default"}`
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct SuggestRequest {
    /// Which acceleration function to run.
    pub mode: SuggestMode,
    /// Current draft — tolerant to eye-typing noise by design.
    /// **P0 content** — never logged.
    pub draft: String,
    /// Number of suggestions requested (UI guidance: 3 max, SPEC §7.A).
    pub n: u8,
    /// Cancellation slot: a new request on the same slot aborts the
    /// previous one (it receives [`SuggestEvent::Aborted`]).
    pub slot: SlotId,
    /// Optional generation constraints.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub constraints: Option<SuggestConstraints>,
    /// Style profile to speak *like the person* (SPEC §5).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style_profile: Option<ProfileId>,
}

/// The four acceleration functions (SPEC §5).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum SuggestMode {
    /// Replies in context, zero keystrokes.
    Replies,
    /// Noisy/telegraphic fragment → full sentence in the user's style.
    Rephrase,
    /// Abbreviation expansion (expert mode).
    Expand,
    /// Continue the draft.
    Continue,
}

/// Generation constraints.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct SuggestConstraints {
    /// Hard cap on suggestion length, characters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_chars: Option<u32>,
    /// Register hint (`famille`, `formel`… — free-form, profile-defined).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub register: Option<String>,
}

/// Events of the `/suggest` SSE stream (SPEC §5.A).
///
/// SSE mapping: the variant name is the SSE `event:` field, the payload is
/// the `data:` JSON. The canonical JSON form below (`{"event": …, "data":
/// …}`) is what the schema documents.
///
/// `non_exhaustive`: streams may gain event kinds; clients ignore unknown
/// events.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[serde(tag = "event", content = "data", rename_all = "lowercase")]
#[non_exhaustive]
pub enum SuggestEvent {
    /// Incremental text for suggestion `i` (append to previous deltas).
    Delta(SuggestDelta),
    /// Terminal event: the complete, post-processed suggestion list.
    Final(SuggestFinal),
    /// Terminal event: generation was cancelled.
    Aborted(SuggestAborted),
}

/// Incremental suggestion text.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct SuggestDelta {
    /// Suggestion index, `0 ≤ i < n`.
    pub i: u8,
    /// Text fragment to append.
    pub text: String,
}

/// Final suggestion list.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct SuggestFinal {
    /// Post-processed suggestions, best first. May be shorter than `n`
    /// (an empty slot costs less than a bad suggestion, SPEC §7.A).
    pub suggestions: Vec<Suggestion>,
}

/// One suggestion.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct Suggestion {
    /// Suggested text. **P0 content** — never logged.
    pub text: String,
    /// Model confidence, higher is better (comparable within one response
    /// only).
    pub score: f64,
    /// Where it came from — memory-sourced suggestions carry a discreet
    /// marker in the UI (SPEC §5.B).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub origin: Option<SuggestionOrigin>,
}

/// Origin of a suggestion.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum SuggestionOrigin {
    /// Generated by the language model.
    Model,
    /// Short-circuited from a recurring phrase in personal memory
    /// (no LLM call — SPEC §5.B).
    Memory,
    /// Produced by the embedded n-gram fallback (LLM down, SPEC §2.C).
    Ngram,
    /// Origin added by a newer hub.
    #[serde(other)]
    Unknown,
}

/// Why a generation ended without a final list.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct SuggestAborted {
    /// Cancellation cause.
    pub reason: AbortReason,
}

/// Cancellation causes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum AbortReason {
    /// A newer request arrived on the same slot.
    Superseded,
    /// The session was deleted mid-generation.
    SessionClosed,
    /// The hub is shutting down.
    Shutdown,
    /// Reason added by a newer hub.
    #[serde(other)]
    Unknown,
}

/// `GET /sessions/{id}/next-chars?prefix=` response — next-character
/// distribution on the warm KV (SPEC §5.A). Never triggers a full
/// generation; feeds adaptive dwell, weighted scanning and Dasher.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct NextCharsResponse {
    /// Character probabilities, descending. BPE→char aggregation hub-side.
    pub dist: Vec<CharProb>,
}

/// Probability of one next character.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct CharProb {
    /// The character (one Unicode scalar value).
    pub ch: char,
    /// Its probability in `[0, 1]`.
    pub p: Normalized,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn suggest_request_matches_spec_example() {
        // SPEC §5.A wire example, verbatim.
        let json = r#"{"mode":"rephrase","draft":"veu eau frache ce soir",
            "n":3,"slot":"main",
            "constraints":{"max_chars":120,"register":"famille"},
            "style_profile":"default"}"#;
        let request: SuggestRequest = serde_json::from_str(json).unwrap();
        assert_eq!(request.mode, SuggestMode::Rephrase);
        assert_eq!(request.n, 3);
        assert_eq!(request.constraints.unwrap().max_chars, Some(120));
    }

    #[test]
    fn sse_events_round_trip() {
        let event = SuggestEvent::Delta(SuggestDelta {
            i: 0,
            text: "Je voudrais".into(),
        });
        let json = serde_json::to_value(&event).unwrap();
        assert_eq!(json["event"], "delta");
        assert_eq!(json["data"]["i"], 0);

        let aborted = SuggestEvent::Aborted(SuggestAborted {
            reason: AbortReason::Superseded,
        });
        let json = serde_json::to_value(&aborted).unwrap();
        assert_eq!(json["data"]["reason"], "superseded");
    }
}
