// SPDX-License-Identifier: Apache-2.0

//! Store record types. Wire/contract types live in `fluence-protocol`;
//! these are the persistence shapes (token hashes, timestamps).

use chrono::{DateTime, Utc};
use fluence_protocol::api::pair::{DeviceKind, Scope};
use secrecy::SecretString;

/// A device to register at pairing time.
#[derive(Debug)]
pub struct NewDevice {
    /// Stable device id (UUID v4, generated by the hub).
    pub device_id: String,
    /// SHA-256 of the bearer token — the token itself is never stored.
    pub token_hash: [u8; 32],
    /// Human name (« Tablette du lit »).
    pub name: String,
    /// Device kind from the pairing request.
    pub kind: DeviceKind,
    /// Scope granted by the pairing window.
    pub scope: Scope,
}

/// A paired device as persisted.
#[derive(Debug, Clone, PartialEq)]
pub struct DeviceRecord {
    /// Stable device id.
    pub device_id: String,
    /// Human name.
    pub name: String,
    /// Device kind.
    pub kind: DeviceKind,
    /// Granted scope.
    pub scope: Scope,
    /// Pairing time.
    pub created_at: DateTime<Utc>,
    /// Revocation time, if revoked.
    pub revoked_at: Option<DateTime<Utc>>,
}

/// A draft as persisted. `text` is **P0** — `Debug` never shows it.
#[derive(Debug)]
pub struct DraftRecord {
    /// Draft text (P0 — behind `SecretString`).
    pub text: SecretString,
    /// Caret position (Unicode scalar values).
    pub caret: u32,
    /// Client-side timestamp of the last keystroke, microseconds — the
    /// kill-test measures loss bounds against it.
    pub updated_at_micros: u64,
}

/// One draft write in a batch flush. `text` is **P0** (behind
/// `SecretString`, so `Debug` never shows it).
#[derive(Debug)]
pub struct DraftWrite {
    /// Session the draft belongs to.
    pub session_id: String,
    /// Draft text (P0).
    pub text: SecretString,
    /// Caret position (Unicode scalar values).
    pub caret: u32,
    /// Client-side timestamp of the last keystroke, microseconds.
    pub updated_at_micros: u64,
}

/// An access-journal entry to append. **Metadata only, never P0**
/// (SPEC §9.A): `detail` describes the action, never user content.
#[derive(Debug, Clone)]
pub struct NewAccessEntry {
    /// Acting device, when authenticated.
    pub device_id: Option<String>,
    /// Stable action name (`pair.window_opened`, `device.paired`,
    /// `device.revoked`, `auth.rejected`…).
    pub action: String,
    /// Non-P0 context (e.g. the route, the device kind).
    pub detail: Option<String>,
}

/// A journal entry as read back.
#[derive(Debug, Clone, PartialEq)]
pub struct AccessEntry {
    /// Row id (monotonic).
    pub id: i64,
    /// When it happened.
    pub at: DateTime<Utc>,
    /// Acting device, when authenticated.
    pub device_id: Option<String>,
    /// Stable action name.
    pub action: String,
    /// Non-P0 context.
    pub detail: Option<String>,
}
